// /lib/proxyCache.js
// ───────────────────────────────────────────────────────────────────────────────
// TinmanApps — ProxyCache v4.0 “Internal Deterministic Edition”
//
// PURPOSE:
// • Replaces all remote GitHub fetching with LOCAL deterministic validation.
// • Ensures category silos ALWAYS exist (appsumo-*.json).
// • Ensures feed-cache.json ALWAYS exists and is valid.
// • Provides a stabilising sanity-sync layer for master-cron.js.
//
// THIS MODULE DOES NOT FETCH ANYTHING EXTERNALLY.
// All content is generated by updateFeed.js and merged by master-cron.
//
// ───────────────────────────────────────────────────────────────────────────────

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const DATA_DIR = path.resolve(__dirname, "../data");
const FEED_CACHE_PATH = path.join(DATA_DIR, "feed-cache.json");

// ✅ Required category silo names (must match updateFeed.js output)
const CATEGORY_FILES = [
  "appsumo-ai.json",
  "appsumo-marketing.json",
  "appsumo-productivity.json",
  "appsumo-software.json",
  "appsumo-courses.json",
  "appsumo-business.json",
  "appsumo-web.json",
  "appsumo-ecommerce.json",
  "appsumo-creative.json",
];

// ───────────────────────────────────────────────────────────────────────────────
// Safe JSON loader
// ───────────────────────────────────────────────────────────────────────────────
function safeRead(file) {
  try {
    return JSON.parse(fs.readFileSync(file, "utf8"));
  } catch {
    return null;
  }
}

// ───────────────────────────────────────────────────────────────────────────────
// Ensures each category silo exists & is valid JSON
// ───────────────────────────────────────────────────────────────────────────────
function ensureValidSilo(filename) {
  const full = path.join(DATA_DIR, filename);

  // File missing → create empty silo
  if (!fs.existsSync(full)) {
    fs.writeFileSync(full, "[]");
    console.log(`⚠️ [ProxyCache] Missing category silo repaired: ${filename}`);
    return [];
  }

  // File exists but JSON corrupted → repair
  const parsed = safeRead(full);
  if (!Array.isArray(parsed)) {
    fs.writeFileSync(full, "[]");
    console.log(`⚠️ [ProxyCache] Corrupt category silo repaired: ${filename}`);
    return [];
  }

  return parsed;
}

// ───────────────────────────────────────────────────────────────────────────────
// backgroundRefresh()
// Called by master-cron.js after updateFeed.js runs.
//
// PURPOSE:
// • Validate all silo files exist & contain valid JSON
// • Ensure feed-cache.json exists & is valid
// • Zero external dependencies
// ───────────────────────────────────────────────────────────────────────────────
export async function backgroundRefresh() {
  console.log("🔍 [ProxyCache] Running background integrity sync…");

  // 1️⃣ Validate all category silos
  let total = 0;
  for (const file of CATEGORY_FILES) {
    const data = ensureValidSilo(file);
    total += Array.isArray(data) ? data.length : 0;
  }

  console.log(`✅ [ProxyCache] All category silos validated (${total} total entries)`);

  // 2️⃣ Validate feed-cache.json
  if (!fs.existsSync(FEED_CACHE_PATH)) {
    fs.writeFileSync(FEED_CACHE_PATH, "[]");
    console.log("⚠️ [ProxyCache] feed-cache.json missing → created baseline file.");
  } else {
    const parsed = safeRead(FEED_CACHE_PATH);
    if (!Array.isArray(parsed)) {
      fs.writeFileSync(FEED_CACHE_PATH, "[]");
      console.log("⚠️ [ProxyCache] feed-cache.json corrupt → repaired.");
    }
  }

  console.log("✅ [ProxyCache] Background sync complete.");
  return { status: "ok", totalEntries: total };
}

// ───────────────────────────────────────────────────────────────────────────────
// Manual trigger (optional)
// ───────────────────────────────────────────────────────────────────────────────
export async function manualRefresh() {
  const out = await backgroundRefresh();
  return { status: "manual refresh complete", ...out };
}

export default { backgroundRefresh, manualRefresh };
